version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web_app/app
hooks:
  BeforeInstall:
    - location: scripts/do_nothing
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root