version: 0.0
os: linux
files:
  - source: /
    destination: ~/web_app
hooks:
  BeforeInstall:
    - location: scripts/build_project
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root