version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web_app/app
    overwrite: yes
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/do_nothing.sh
      timeout: 300
  BeforeInstall:
    - location: scripts/do_nothing.sh
      timeout: 300
  AfterInstall:
    - location: scripts/do_nothing.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300