version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web_app
hooks:
  BeforeInstall:
    - location: scripts/set_env
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root