version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/web_app/app
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStop:
    - location: scripts/do_nothing
      timeout: 300
  BeforeInstall:
    - location: scripts/do_nothing
      timeout: 300
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/start_server
      timeout: 300