version: 0.0
os: linux
files:
  - source: /
    destination: ~/web_app
hooks:
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root